name: tests unitaires

on: [push]  # Déclenche le workflow à chaque push

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu

    steps:
    - uses: actions/checkout@v3  # Vérifie le code depuis le dépôt

    - name: Set up Python for Demo
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Spécifie la version de Python à utiliser

    - name: Run tests
      run: pytest TP1/test.py  # Exécute les tests dans TP1/test.py
